### ISSUE TITLE
Updates to service_add_edit.html

### ISSUE THREAD

**Issue by chasebank** [roberttstephens/not_uniformity#61]
Made some updates to this but there's more work needed. What's there is sort of a temporary mash up of new and old.

Rather than have a disabled drop down menu for the person already selected, I moved that pre-selected name to the title bar. I think this makes more sense both design wise and UX. Little less confusing.

Some things need to be made dynamic though.
- [x] Title wrapper in the example needs a "caregiver" class, which would reverse to "client" if assigning a caregiver to a client. Maybe {{ role }} sense since this should be the role of the person where the request originated.
- [x] Title reads "New Client for Chase Whiteside". The name should obviously be dynamic, and use of the word Caregiver needs to reverse to "Client" if we're assigning a client to a particular caregiver. So basically the opposite of our current use of {{role}}. Maybe {{role-opposite))
- [x] "Client Information"  same as above. {{role-opposite}}

**Drop down
- [x] Things associated with the field such as label, placeholder, "for" attributes would also need {{role-opposite}}

Dropdowns need a placeholder which is a first option set to selected and disabled, and then the other options would dynamically follow.
- [ ] drop down placeholder

Maybe something like this

```html
<label for="{{ role-opposite }}_id>{{ role-opposite }} Name*</label>
<select id="{{ role-opposite }}_id" name="{{ role-opposite }}_id">
    <option selected disabled>Choose a {{ role-opposite }}</option>
    <option value="1">Chase Whiteside</option>
</select>
```

**Comment by roberttstephens** [comment]
Also, add logic to the view to prevent an invalid state. Ensure that either ?client_id= or ?caregiver_id= is specified (not both, not neither).

**Comment by chasebank** [comment]
This is the old code for the disabled form field, for reference, that shows the name of the person that a service is being added to.

So click on a caregiver, then click 'add client' and the below filed would show the caregiver's name in a disabled field. Instead, we need to use a similar approach in the header to say "New Client for *Caregiver Name*".

`{% if caregiver_disabled %} {{ render_field(form.caregiver_id, disabled=True) }} {% else %} {{ render_field(form.caregiver_id) }} {% endif %}`
