### ISSUE TITLE
Total # of expired and expiring soon forms aren't showing on caregiver/client page.

### ISSUE THREAD

**Issue by chasebank** [roberttstephens/not_uniformity#65]
http://form.management/caregivers/1
http://form.management/client/1

The info is in the dom but a styling issue has them hidden for some reason.

**Comment by roberttstephens** [comment]
@chasebank There are two instances of `font-size: 0 !important;` causing the text to not appear. It may need other styling changes as well.

1. `div.caregiver .profile-info .summary`
2. `.container .profile-info .summary`
